### PR TITLE
Forbid unsafe, edition 2021, MSRV 1.65, more lints

### PR DESCRIPTION
**Pull request by pitaj**
- Forbid unsafe code and remove legacy unsafe-related docs
- Switch to edition 2021
- Set `rust-version` in Cargo.toml to 1.65
- Enable pedantic clippy lints
- Enable more rustc lints (see daf57cd0185014e6cf5bf154cb731b6345ff35f1 for details on the exceptions)

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -240,7 +237,41 @@
...
+    trivial_numeric_casts,
+    unreachable_pub,
+    unused_extern_crates,
+    unused_import_braces,
+    unused_lifetimes,
+    unused_macro_rules,
+    unused_qualifications,
+    unused_tuple_struct_fields,
+    variant_size_differences
+)]
```
Comment (udoprog) [inline src/lib.rs]: Scary looking list!

Now I'm not entirely sure enabling `deny` on such an exhaustive list of lints for library crates is future proof. If rustc adds future lint violations which falls under these (maybe something wasn't caught previously) wouldn't that cause a compilation error?

Could you make sure this is not the case? Otherwise I'm :+1:.

Comment (udoprog) [reply src/lib.rs]: So I don't believe this is sufficiently guaranteed to be future proof unfortunately with this list: https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html

Now a better way to ensure that a specific crate avoids these now and into the future is to only enable them for the CI build, like through some feature flag.

**Comment by udoprog** [comment]
:warning: some minor incompatibilities might be introduced by #14, they should be fairly minor all things considering.

File: src/lib.rs (hunk 1 above)
Comment (pitaj) [reply src/lib.rs]: That anti-pattern is specifically about `deny(warnings)`, because they could set a given lint to warn by default (which can be done without an edition). It's not about changing existing lints. And it doesn't apply to clippy lints, because they aren't enabled unless you're running clippy.

If you're really worried about it, I would have just enabled them as warnings instead - that way you'll still see them in your editor unconditionally.

Regardless, you could have made it a little nicer by leaving the long list of deny lints in a single deny(). That would have left less `cfg_attr` noise.

Also, it there a reason you changed `forbid(unsafe)` to `deny(unsafe)`? Forbid had stronger guarantees - you can't re-allow it later on. Changing it to deny kind of defeats the purpose.

Comment (udoprog) [reply src/lib.rs]: > That anti-pattern is specifically about deny(warnings), because they could set a given lint to warn by default (which can be done without an edition). It's not about changing existing lints. And it doesn't apply to clippy lints, because they aren't enabled unless you're running clippy.

Specifically yes, but reading the full article should convey that it applies lints that might *change* in the future as well. I.e. it would only be appropriate to `deny` something that is very unlikely to ever change, like `missing_docs`. I'm not sure how it applies in the future to the rest of the lints but better safe than sorry. Catching them in CI (i.e. as they're introduced as a change in this crate) fulfills the same role of ensuring idiomatic code.

> If you're really worried about it, I would have just enabled them as warnings instead - that way you'll still see them in your editor unconditionally.

Yep, this sounds like a better option! Then you'd only need to add `-D warnings` in CI. If you feel like doing a follow up PR, feel free to!

> Regardless, you could have made it a little nicer by leaving the long list of deny lints in a single deny(). That would have left less `cfg_attr` noise.

Yeah, all though I prefer the `cfg_attr` noise *in this* instance ;). If it's just a single `warn` though that would be fine.

> Also, it there a reason you changed `forbid(unsafe)` to `deny(unsafe)`? Forbid had stronger guarantees - you can't re-allow it later on. Changing it to deny kind of defeats the purpose.

Ah, no. That was a mistake during editing. What exactly is the difference between `forbid` and `deny`?

Comment (udoprog) [reply src/lib.rs]: Hm, regarding `-D warnings`. Thinking about it for a minute I wouldn't be entirely happy about the workflow of emitting warnings *by default* either so they should probably still be under a `--cfg` flag. The reason is that they can be quite noisy for downstream users if they're introduced by compiler upgrades. There's nothing the downstream user can do directly other than report it upstream and/or upgrade the crate.

Comment (pitaj) [reply src/lib.rs]: > What exactly is the difference between forbid and deny?

`deny` can be overridden by an `allow` later on. `forbid` can not.

> The reason is that they can be quite noisy for downstream users if they're introduced by compiler upgrades.

Warnings in dependencies are hidden from downstream users by cargo. Though it may still be useful to have `-D warnings` in CI, probably when running clippy.

Comment (udoprog) [reply src/lib.rs]: OK, if that's true then changing it to always warn and `-D warnings` in CI is fine! Cheers!
